apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello-world
  template:
    metadata:
      name: hello-world
      labels:
        name: hello-world
    spec:
      containers:
        - name: hello-world
          image: ltodt/get-started:part1
          ports:
            - name: hello-world
              containerPort: 80
